# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: more_possessive 1.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "more_possessive".freeze
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Brian Clubb".freeze, "Jamie Flournoy".freeze, "Nick Howard".freeze]
  s.date = "2017-02-26"
  s.description = "Rails plugin that lets you get a possessive form of a string for use on sites".freeze
  s.email = "alizain.feerasta@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/core_ext/string/inflections.rb",
    "more_possessive.gemspec",
    "rails/init.rb",
    "test/helper.rb",
    "test/test_possessive.rb"
  ]
  s.homepage = "http://github.com/alizain/more_possessive".freeze
  s.rubygems_version = "2.6.4".freeze
  s.summary = "Rails plugin that lets you get a possessive form of a string for use on sites".freeze
end

